#!/usr/bin/env python3
"""Produce a run-local copy of an HTML slide template carrying a client's palette.

    python apply_brand.py brand_profile.json proposal-assets/templates/html-generic \\
        -o comms/<client>/runs/<run>/template

Copies the template directory into the run, then appends a generated `:root { … }` override
to the copied theme.css. The template already exposes its whole palette as CSS custom
properties, so an appended override is enough — no selector surgery, no layout edits, and
render_html.py stays at zero diff.

The copy is deliberate: a run keeps a snapshot of the exact template it was built on, which
is better provenance than a flag on the renderer. Point the plan's `template.path` at the
copy, not at the shared template.

Two hard stops:

  * `approval.approved_by` must be populated. A brand profile nobody approved is a
    lookalike, and this script will not build one.
  * Every ink/canvas pair is checked for WCAG contrast against
    `accessibility.min_contrast_ratio`. A palette that produces unreadable slides fails
    here rather than at the town hall.

STATUS (v0.1): this recolours; it does not rebrand. It deliberately does NOT alter layouts,
and it does NOT place the client's logo — that needs an asset this repo does not have and a
placement judgement a script should not make. Both stay practitioner steps and both appear
in the QA report's human checklist. The result is a proof-of-concept template carrying the
client's colours, never the client's approved deck. Say exactly that at handover.
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

# Brand palette key -> the CSS custom property it drives in theme.css.
PALETTE_MAP = {
    "ink": "--ink",
    "ink_soft": "--ink-soft",
    "muted": "--muted",
    "accent": "--accent",
    "rule": "--rule",
    "canvas": "--canvas",
    "panel": "--panel",
}

# Pairs that must stay legible: (foreground key, background key).
CONTRAST_PAIRS = [
    ("ink", "canvas"),
    ("ink_soft", "canvas"),
    ("ink", "panel"),
    ("ink_soft", "panel"),
    ("accent", "canvas"),
]

HEX_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


def hex_to_rgb(value):
    value = value.lstrip("#")
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))


def relative_luminance(rgb):
    """WCAG 2.1 relative luminance."""
    channels = []
    for raw in rgb:
        c = raw / 255
        channels.append(c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4)
    r, g, b = channels
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast_ratio(fg_hex, bg_hex):
    l1 = relative_luminance(hex_to_rgb(fg_hex))
    l2 = relative_luminance(hex_to_rgb(bg_hex))
    lighter, darker = max(l1, l2), min(l1, l2)
    return (lighter + 0.05) / (darker + 0.05)


def palette_hex(brand):
    """Flatten the profile's palette to {key: '#rrggbb'}, skipping malformed entries."""
    out = {}
    for key, value in (brand.get("palette") or {}).items():
        if isinstance(value, dict) and HEX_RE.match(str(value.get("hex", ""))):
            out[key] = value["hex"]
    return out


def build_override(brand, colours):
    """The :root block appended to the copied theme.css."""
    lines = [
        "",
        "/* ------------------------------------------------------------------",
        f"   Brand override — {brand.get('client', 'client')}",
        f"   Generated by apply_brand.py from a {brand.get('source', 'unknown')} profile,",
        f"   approved by {brand.get('approval', {}).get('approved_by', '—')} on "
        f"{brand.get('approval', {}).get('approved_date', '—')}.",
        "",
        "   This recolours the generic proof-of-concept template. It does not make the",
        "   deck the client's approved template, and it places no logo.",
        "   ------------------------------------------------------------------ */",
        ":root {",
    ]
    for key, prop in PALETTE_MAP.items():
        if key in colours:
            lines.append(f"  {prop}: {colours[key]};")

    # accent-dim is derived: the accent at low opacity over the canvas, so panels
    # tinted with it stay on-brand without the profile having to name a ninth colour.
    if "accent" in colours:
        r, g, b = hex_to_rgb(colours["accent"])
        lines.append(f"  --accent-dim: rgba({r}, {g}, {b}, 0.12);")

    typo = brand.get("typography", {})
    heading, body = typo.get("heading", {}), typo.get("body", {})
    fallback = typo.get("web_safe_fallback", "system-ui, sans-serif")
    if body.get("family"):
        stack = ", ".join(
            [f'"{body["family"]}"'] + list(body.get("fallbacks", [])) + [fallback]
        )
        lines.append(f"  --font-sans: {stack};")
    if heading.get("family"):
        stack = ", ".join(
            [f'"{heading["family"]}"'] + list(heading.get("fallbacks", [])) + [fallback]
        )
        lines.append(f"  --font-serif: {stack};")

    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("brand", type=Path, help="brand_profile.json")
    ap.add_argument("template_dir", type=Path, help="HTML template directory to copy")
    ap.add_argument("-o", "--out", type=Path, required=True,
                    help="Destination directory for the branded copy")
    ap.add_argument("--force", action="store_true", help="Overwrite an existing destination")
    args = ap.parse_args()

    brand = json.loads(args.brand.read_text(encoding="utf-8"))

    approval = brand.get("approval") or {}
    if not approval.get("approved_by"):
        sys.exit(
            "brand profile has no approval.approved_by — stop and ask the client for an "
            "approved template or brand guidelines. Do not build a lookalike."
        )

    if not (args.template_dir / "theme.css").is_file():
        sys.exit(f"{args.template_dir} has no theme.css — is it an HTML template directory?")

    colours = palette_hex(brand)
    if not colours:
        sys.exit("brand profile has no usable palette — nothing to apply")

    min_ratio = (brand.get("accessibility") or {}).get("min_contrast_ratio", 4.5)
    failures, reported = [], []
    for fg, bg in CONTRAST_PAIRS:
        if fg in colours and bg in colours:
            ratio = contrast_ratio(colours[fg], colours[bg])
            reported.append((fg, bg, ratio))
            if ratio < min_ratio:
                failures.append(f"{fg} on {bg}: {ratio:.2f}:1 (needs {min_ratio}:1)")

    # Fail before writing anything. A half-branded template left on disk is worse than
    # none, because the next command will happily render from it.
    if failures:
        for fg, bg, ratio in reported:
            print(f"  contrast {fg} on {bg}: {ratio:.2f}:1"
                  f"{'  OK' if ratio >= min_ratio else '  FAIL'}")
        for f in failures:
            print(f"  ERROR {f}", file=sys.stderr)
        sys.exit("palette fails the accessibility floor — fix the profile, not the template. "
                 "Nothing was written.")

    if args.out.exists():
        if not args.force:
            sys.exit(f"{args.out} already exists — pass --force to overwrite")
        shutil.rmtree(args.out)
    shutil.copytree(args.template_dir, args.out)

    theme = args.out / "theme.css"
    theme.write_text(theme.read_text(encoding="utf-8") + build_override(brand, colours),
                     encoding="utf-8")

    # Keep the copied profile pointing at itself, so a plan validated against it and a deck
    # rendered from it can never disagree about which template was used.
    profile_path = args.out / "template_profile.json"
    if profile_path.is_file():
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        profile["template"] = str(args.out)
        profile["brand_applied"] = {
            "client": brand.get("client"),
            "approved_by": approval.get("approved_by"),
            "approved_date": approval.get("approved_date"),
        }
        profile_path.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")

    print(f"Branded template -> {args.out}")
    print(f"  palette: {', '.join(f'{k}={v}' for k, v in sorted(colours.items()))}")
    for fg, bg, ratio in reported:
        print(f"  contrast {fg} on {bg}: {ratio:.2f}:1  OK")

    print("  No logo placed and no layout altered — both remain practitioner steps.")
    print("  This is the generic PoC template in the client's colours, NOT their "
          "approved template.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
