#!/usr/bin/env python3
"""Turn a comms plan into a PowerPoint deck (Stage 3b, briefing_deck channel).

    python build_pptx.py comms_plan.json --theme deck_theme.json -o comms/<run>
    NODE_PATH="$(npm root -g)" node comms/<run>/build_deck.js

THE FROM-SCRATCH ROUTE ONLY. When the client has an approved .potx, do NOT use this —
profile it with profile_template.py, validate the plan with build_deck.py, and assemble
through the `pptx` skill's template workflow (unzip -> edit ppt/slides/slideN.xml ->
rezip). A deck built from scratch is not an approved-template deck however close the
colours are, and someone notices.

Emits a Node script against pptxgenjs rather than writing OOXML here, so the build is
inspectable before it runs and the `pptx` skill's footguns are encoded once: layout set
before any slide is added, hex colours with no leading '#', a fresh options object per
call, bullets via `bullet: true` with `breakLine` on all but the last item, and speaker
notes through addNotes rather than a text box.

Every content slide carries speaker notes. A cascade deck without them gets improvised,
and the improvisation is what the audience remembers — so a slide with none gets a
visible placeholder note saying so rather than shipping silently bare.

A [GAP] block renders as a visible amber panel, exactly as it does in the Markdown draft
and the .docx. It is never dropped and never filled with substitute text.

STATUS (v0.2): generates and checks; it does not run node itself, so a failed build
leaves an inspectable script rather than a half-written .pptx. It places no logo.
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_markdown import ordered_parts  # noqa: E402

# Layout -> the renderer that draws it. Keys match the plan's `layout` values.
KNOWN_LAYOUTS = {"title-slide", "section-header", "title-and-content",
                 "two-content", "table", "timeline", "metric-row"}


def js(value):
    return json.dumps(value, ensure_ascii=False)


def hexof(theme, role, default):
    """pptxgenjs corrupts the file on a leading '#' or an 8-digit hex."""
    value = (theme.get("palette") or {}).get(role, default)
    return str(value).lstrip("#").upper()[:6]


def face(theme, role, default="Calibri"):
    stack = (theme.get("typography") or {}).get(role) or []
    return stack[0] if stack else default


def blocks_by_placeholder(part):
    out = {}
    for b in part.get("blocks", []):
        out.setdefault(b.get("placeholder", "body"), []).append(b)
    return out


def flat_text(block):
    c = block.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return " ".join(str(i) for i in c)
    return ""


def pptxgen_check():
    if not shutil.which("node"):
        return False, "", "node is not on PATH"
    root = ""
    try:
        root = subprocess.run(["npm", "root", "-g"], capture_output=True, text=True,
                              timeout=30).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    import os
    env = dict(os.environ)
    if root:
        env["NODE_PATH"] = root
    probe = subprocess.run(["node", "-e", "require.resolve('pptxgenjs')"],
                           capture_output=True, text=True, timeout=30, env=env)
    if probe.returncode != 0:
        return False, root, ("pptxgenjs is not resolvable — run `npm install -g pptxgenjs`, "
                             "then build with NODE_PATH=\"$(npm root -g)\"")
    return True, root, ""


def build_js(plan, theme, out_dir):
    ink, soft = hexof(theme, "ink", "#12314F"), hexof(theme, "ink_soft", "#414D59")
    accent, panel = hexof(theme, "accent", "#0F6D7A"), hexof(theme, "panel", "#EEF3F5")
    canvas, rule = hexof(theme, "canvas", "#FFFFFF"), hexof(theme, "rule", "#D3DEE2")
    head_font, body_font = face(theme, "heading"), face(theme, "body")

    L = ["// Generated by build_pptx.py — inspect before running.",
         "// Build with:  NODE_PATH=\"$(npm root -g)\" node build_deck.js",
         "const pptxgen = require('pptxgenjs');",
         "const pres = new pptxgen();",
         "pres.layout = 'LAYOUT_WIDE';   // 13.3 x 7.5in — set BEFORE any slide is added",
         f"const INK={js(ink)}, SOFT={js(soft)}, ACCENT={js(accent)};",
         f"const PANEL={js(panel)}, CANVAS={js(canvas)}, RULE={js(rule)};",
         f"const HEAD={js(head_font)}, BODY={js(body_font)};",
         "const GAP_BG='F8EEDD', GAP_INK='8A5410';",
         "",
         "function slideBase() {",
         "  const s = pres.addSlide();",
         "  s.background = { color: CANVAS };",
         "  return s;",
         "}",
         "// Fresh options object per call — pptxgenjs mutates them in place.",
         "function titleOpts(y) { return { x:0.6, y:y, w:12.1, h:0.9, fontFace:HEAD,",
         "  fontSize:30, bold:true, color:INK, valign:'top', margin:0 }; }",
         "function kickerOpts()  { return { x:0.6, y:0.45, w:12.1, h:0.32, fontFace:BODY,",
         "  fontSize:12, color:ACCENT, charSpacing:1.4, margin:0 }; }",
         "function bodyOpts(x,y,w,h) { return { x:x, y:y, w:w, h:h, fontFace:BODY,",
         "  fontSize:15, color:SOFT, valign:'top', margin:0, lineSpacingMultiple:1.18 }; }",
         "function gapOpts(y) { return { x:0.6, y:y, w:12.1, h:1.5, fontFace:BODY, fontSize:14,",
         "  color:GAP_INK, bold:true, fill:{color:GAP_BG}, valign:'top', margin:12 }; }",
         "function bullets(items) { return items.map((t,i) => ({ text:t,",
         "  options:{ bullet:true, breakLine: i < items.length-1, paraSpaceAfter:7 } })); }",
         ""]

    slide_no = 0
    for section, part in ordered_parts(plan):
        slide_no += 1
        layout = part.get("layout") or "title-and-content"
        if layout not in KNOWN_LAYOUTS:
            layout = "title-and-content"
        ph = blocks_by_placeholder(part)
        L.append(f"// --- slide {slide_no}: {part['slide_id']} ({layout})")
        L.append("{ const s = slideBase();")

        kicker = ph.get("kicker")
        if kicker and layout != "title-slide":
            L.append(f"  s.addText({js(flat_text(kicker[0]).upper())}, kickerOpts());")

        if layout == "title-slide":
            client = flat_text(ph.get("client", [{}])[0]) if ph.get("client") else plan.get("client", "")
            sub = flat_text(ph.get("subtitle", [{}])[0]) if ph.get("subtitle") else ""
            meta = flat_text(ph.get("meta", [{}])[0]) if ph.get("meta") else ""
            L.append(f"  s.addShape(pres.ShapeType.rect, {{ x:0, y:0, w:13.33, h:7.5, fill:{{color:PANEL}} }});")
            L.append(f"  s.addText({js(client.upper())}, {{ x:0.8, y:1.5, w:11.7, h:0.35,"
                     f" fontFace:BODY, fontSize:13, color:ACCENT, charSpacing:1.8, margin:0 }});")
            L.append(f"  s.addText({js(part.get('title',''))}, {{ x:0.8, y:2.0, w:11.7, h:1.7,"
                     f" fontFace:HEAD, fontSize:40, bold:true, color:INK, margin:0 }});")
            if sub:
                L.append(f"  s.addText({js(sub)}, {{ x:0.8, y:3.75, w:11.7, h:0.6,"
                         f" fontFace:BODY, fontSize:17, color:SOFT, margin:0 }});")
            L.append(f"  s.addShape(pres.ShapeType.line, {{ x:0.8, y:4.6, w:3.2, h:0,"
                     f" line:{{ color:ACCENT, width:2.5 }} }});")
            if meta:
                L.append(f"  s.addText({js(meta)}, {{ x:0.8, y:6.5, w:11.7, h:0.4,"
                         f" fontFace:BODY, fontSize:11, color:SOFT, margin:0 }});")
        else:
            L.append(f"  s.addText({js(part.get('title',''))}, titleOpts(0.85));")
            L.append("  s.addShape(pres.ShapeType.line, { x:0.6, y:1.72, w:12.1, h:0,"
                     " line:{ color:RULE, width:1 } });")

            if layout == "two-content":
                for side, x in (("left", 0.6), ("right", 6.95)):
                    head = ph.get(side + "_heading")
                    if head:
                        L.append(f"  s.addText({js(flat_text(head[0]))}, {{ x:{x}, y:2.0, w:5.75,"
                                 f" h:0.4, fontFace:HEAD, fontSize:16, bold:true, color:INK, margin:0 }});")
                    for b in ph.get(side, []):
                        _emit_block(L, b, x, 2.55, 5.75, 4.3)
            elif layout == "table":
                for b in ph.get("table", []) or ph.get("body", []):
                    _emit_block(L, b, 0.6, 2.05, 12.1, 4.8)
            elif layout == "timeline":
                for b in ph.get("phases", []) or ph.get("body", []):
                    _emit_block(L, b, 0.6, 2.05, 12.1, 4.8)
            else:
                for b in ph.get("body", []):
                    _emit_block(L, b, 0.6, 2.05, 12.1, 4.8)

        notes = part.get("speaker_notes")
        if not notes and layout != "title-slide":
            notes = ("[NO SPEAKER NOTES RECORDED] A cascade deck without notes gets "
                     "improvised, and the improvisation is what the audience remembers. "
                     "Write them before this is presented.")
        if notes:
            L.append(f"  s.addNotes({js(notes)});")
        L.append("}")
        L.append("")

    L += [f"pres.writeFile({{ fileName: __dirname + '/deck.pptx' }})",
          "  .then(f => console.log('Wrote ' + f));"]
    return "\n".join(L) + "\n"


def _emit_block(L, block, x, y, w, h):
    if block.get("gap"):
        note = "[GAP] " + (block.get("gap_note") or "Not covered by the bank or the brief.")
        L.append(f"  s.addText({js(note)}, gapOpts({y}));")
        return

    kind, content = block["kind"], block["content"]

    if kind == "bullets":
        items = content if isinstance(content, list) else [content]
        L.append(f"  s.addText(bullets({js([str(i) for i in items])}), "
                 f"bodyOpts({x},{y},{w},{h}));")
    elif kind == "table":
        headers = content.get("headers", [])
        rows = content.get("rows", [])
        head_row = ("[" + ", ".join(
            "{ text:" + js(str(hh)) + ", options:{ bold:true, color:INK, fill:{color:PANEL} } }"
            for hh in headers) + "]")
        body_rows = ", ".join(
            "[" + ", ".join(js(str(c)) for c in r) + "]" for r in rows)
        L.append(f"  s.addTable([{head_row}, {body_rows}], {{ x:{x}, y:{y}, w:{w},"
                 f" fontFace:BODY, fontSize:12, color:SOFT, border:{{ type:'solid',"
                 f" color:RULE, pt:1 }}, autoPage:false }});")
    elif kind == "phases":
        items = content if isinstance(content, list) else [content]
        lines = []
        for p in items:
            when = str(p.get("when") or p.get("date") or "")
            name = str(p.get("name") or p.get("label") or "")
            detail = str(p.get("detail") or p.get("description") or "")
            lines.append(f"{name} — {when}" + (f": {detail}" if detail else ""))
        L.append(f"  s.addText(bullets({js(lines)}), bodyOpts({x},{y},{w},{h}));")
    else:
        items = content if isinstance(content, list) else [content]
        text = "\n".join(str(i) for i in items if str(i).strip())
        if text:
            L.append(f"  s.addText({js(text)}, bodyOpts({x},{y},{w},{h}));")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan", type=Path)
    ap.add_argument("--theme", type=Path, required=True,
                    help="deck_theme.json from apply_brand.py")
    ap.add_argument("-o", "--out", type=Path, required=True, help="Output directory")
    args = ap.parse_args()

    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    theme = json.loads(args.theme.read_text(encoding="utf-8"))

    if plan.get("channel") != "briefing_deck":
        sys.exit(f"build_pptx.py handles the briefing_deck channel; got '{plan.get('channel')}'")
    if not theme.get("approved_by"):
        sys.exit("deck theme carries no brand approval — stop and ask before producing")
    if (theme.get("deck") or {}).get("potx_path"):
        sys.exit("this brand names a client .potx — do NOT build from scratch. Profile it with "
                 "profile_template.py, validate with build_deck.py, then assemble through the "
                 "`pptx` skill's template workflow.")

    args.out.mkdir(parents=True, exist_ok=True)
    script = args.out / "build_deck.js"
    script.write_text(build_js(plan, theme, args.out), encoding="utf-8")

    slides = sum(1 for _ in ordered_parts(plan))
    gaps = sum(1 for _, p in ordered_parts(plan) for b in p["blocks"] if b.get("gap"))
    bare = sum(1 for _, p in ordered_parts(plan)
               if not p.get("speaker_notes") and p.get("layout") != "title-slide")

    print(f"Wrote {script}  [{slides} slides, {gaps} gap(s)]")
    if bare:
        print(f"  {bare} content slide(s) have no speaker notes — a placeholder note says so "
              f"on each; write them before this is presented.")

    ok, root, remedy = pptxgen_check()
    if ok:
        print(f'  build with:  NODE_PATH="{root}" node {script}')
    else:
        print(f"  NOT BUILDABLE YET: {remedy}", file=sys.stderr)

    print("  FROM-SCRATCH build on the client's colours — this is NOT their approved "
          "template. Say so at handover.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
